### ISSUE TITLE
how to block IOS to auto open portal ?

### ISSUE THREAD

**Issue by aircraft008** [wifidog/wifidog-gateway#14] opened 2014-04-24 09:12 UTC
I want to blokc the IOS to auto open the portal, but still need to login over safari or other app.
Since IPs of  FQDNs will change because of load balancing and geo location and wifidog just support use ip in it's firewall. So how to whitelist FQDNs ？ 

FQDNs like these:
www.appleiphonecell.com
captive.apple.com
www.apple.com
www.itools.info
www.ibook.info
www.airport.us
www.thinkdifferent.us

**Comment by mhaas** [comment] 2015-03-11 21:57
Is this a duplicate of #7? Handling multiple IPs per FQDN can also be handled via #70.

**Comment by sinkcup** [comment] 2015-03-12 02:17
see #65 , compile the lastest version
add this root domain to conf:

    FirewallRule allow tcp to apple.com
    FirewallRule allow tcp to icloud.com

**Comment by mhaas** [comment] 2015-03-12 06:27
Let's document this in wifidog.conf then. Will do later.

**Closed** 2015-03-13 08:32 UTC
