### ISSUE TITLE
About ios7

### ISSUE THREAD

**Issue by wangyonghe** [wifidog/wifidog-gateway#11] opened 2013-10-22 06:21 UTC
The captive portal cannot be opened automatically when iphone 5s connects.

**Comment by mhaas** [comment] 2015-03-11 21:52
Is this still a problem or can the issue be closed?

**Comment by mhaas** [comment] 2015-03-12 07:05
Duplicate of #14

**Closed by mhaas** 2015-03-12 07:05 UTC
Labels: duplicate

**Comment by hbl0307106015** [comment] 2015-05-28 02:24
Hi, all,
    I am using wifidog-20130917 openwrt-1407. The captive portal can not be open whatever wireless client connect to my ap.
    below is the log running wifidog -d 9 -f -c /etc/wifidog.conf

[6][Tue May 26 12:37:52 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:37:52 2015][9873](httpd_thread.c:71) No valid request received from 192.168.1.172
[7][Tue May 26 12:37:52 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:37:52 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:37:52 2015][9873](httpd_thread.c:71) No valid request received from 192.168.1.172
[7][Tue May 26 12:37:52 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:37:57 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:71) No valid request received from 192.168.1.172
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:37:57 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:65) Processing request from 192.168.1.172
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:66) Calling httpdProcessRequest() for 192.168.1.172
[6][Tue May 26 12:37:57 2015][9873](http.c:124) Got client MAC address for ip 192.168.1.172: 9c:99:a0:40:df:4e
[6][Tue May 26 12:37:57 2015][9873](http.c:134) Captured 192.168.1.172 requesting [http%3A//dns.weixin.qq.com/cgi-bin/micromsg-bin/newgetdns%3Fuin%3D0%26clientversion%3D637599817%26scene%3D0%26net%3D1%26md5%3Dbbfad2a27141b1fe1a2f6d252e55763a%26devicetype%3Dandroid-19%26lan%3Den%26sigver%3D1] and re-directing them to login page
[7][Tue May 26 12:37:57 2015][9873](http.c:214) Redirecting client browser to http://192.168.1.100:80/login/?gw_address=192.168.1.1&gw_port=2060&gw_id=143BCEEC320&mac=9c:99:a0:40:df:4e&url=http%3A//dns.weixin.qq.com/cgi-bin/micromsg-bin/newgetdns%3Fuin%3D0%26clientversion%3D637599817%26scene%3D0%26net%3D1%26md5%3Dbbfad2a27141b1fe1a2f6d252e55763a%26devicetype%3Dandroid-19%26lan%3Den%26sigver%3D1
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:68) Returned from httpdProcessRequest() for 192.168.1.172
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:37:57 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:65) Processing request from 192.168.1.172
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:66) Calling httpdProcessRequest() for 192.168.1.172
[6][Tue May 26 12:37:57 2015][9873](http.c:124) Got client MAC address for ip 192.168.1.172: 9c:99:a0:40:df:4e
[6][Tue May 26 12:37:57 2015][9873](http.c:134) Captured 192.168.1.172 requesting [http%3A//szshort.weixin.qq.comhttp%3A/szshort.weixin.qq.com/cgi-bin/micromsg-bin/newauth] and re-directing them to login page
[7][Tue May 26 12:37:57 2015][9873](http.c:214) Redirecting client browser to http://192.168.1.100:80/login/?gw_address=192.168.1.1&gw_port=2060&gw_id=143BCEEC320&mac=9c:99:a0:40:df:4e&url=http%3A//szshort.weixin.qq.comhttp%3A/szshort.weixin.qq.com/cgi-bin/micromsg-bin/newauth
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:68) Returned from httpdProcessRequest() for 192.168.1.172
[7][Tue May 26 12:37:57 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:38:00 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:38:00 2015][9873](httpd_thread.c:65) Processing request from 192.168.1.172
[7][Tue May 26 12:38:00 2015][9873](httpd_thread.c:66) Calling httpdProcessRequest() for 192.168.1.172
[6][Tue May 26 12:38:00 2015][9873](http.c:124) Got client MAC address for ip 192.168.1.172: 9c:99:a0:40:df:4e
[6][Tue May 26 12:38:00 2015][9873](http.c:134) Captured 192.168.1.172 requesting [http%3A//111.13.142.10%3A80/mibind/http-bind%3Ft%3D197] and re-directing them to login page
[7][Tue May 26 12:38:00 2015][9873](http.c:214) Redirecting client browser to http://192.168.1.100:80/login/?gw_address=192.168.1.1&gw_port=2060&gw_id=143BCEEC320&mac=9c:99:a0:40:df:4e&url=http%3A//111.13.142.10%3A80/mibind/http-bind%3Ft%3D197
[7][Tue May 26 12:38:00 2015][9873](httpd_thread.c:68) Returned from httpdProcessRequest() for 192.168.1.172
[7][Tue May 26 12:38:00 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:38:02 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:38:02 2015][9873](httpd_thread.c:71) No valid request received from 192.168.1.172
[7][Tue May 26 12:38:02 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:38:10 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread
[7][Tue May 26 12:38:10 2015][9873](httpd_thread.c:65) Processing request from 192.168.1.172
[7][Tue May 26 12:38:10 2015][9873](httpd_thread.c:66) Calling httpdProcessRequest() for 192.168.1.172
[6][Tue May 26 12:38:10 2015][9873](http.c:124) Got client MAC address for ip 192.168.1.172: 9c:99:a0:40:df:4e
[6][Tue May 26 12:38:10 2015][9873](http.c:134) Captured 192.168.1.172 requesting [http%3A//111.13.142.10%3A80/mibind/http-bind%3Ft%3D634] and re-directing them to login page
[7][Tue May 26 12:38:10 2015][9873](http.c:214) Redirecting client browser to http://192.168.1.100:80/login/?gw_address=192.168.1.1&gw_port=2060&gw_id=143BCEEC320&mac=9c:99:a0:40:df:4e&url=http%3A//111.13.142.10%3A80/mibind/http-bind%3Ft%3D634
[7][Tue May 26 12:38:10 2015][9873](httpd_thread.c:68) Returned from httpdProcessRequest() for 192.168.1.172
[7][Tue May 26 12:38:10 2015][9873](httpd_thread.c:73) Closing connection with 192.168.1.172
[6][Tue May 26 12:38:12 2015][9873](gateway.c:474) Received connection from 192.168.1.172, spawning worker thread

**Comment by hbl0307106015** [comment] 2015-05-28 02:30
By the way, there is a br-lan interface with eth0.1(LAN) and wlan0, I just want to test wifidog in my local network wiht LAN. below is my configuration file:

GatewayID default
ExternalInterface eth0.1
GatewayInterface br-lan
HtmlMessageFile /etc/wifidog-msg.html
AuthServer {
    Hostname 192.168.1.100
    SSLavailable no
    Path /
}

ClientTimeout 7200

FirewallRuleSet global {

}
FirewallRuleSet validating-users {
FirewallRule allow to 0.0.0.0/0
}
FirewallRuleSet known-users {
FirewallRule allow to 0.0.0.0/0
}
FirewallRuleSet unknown-users {
FirewallRule allow udp port 53
FirewallRule allow tcp port 53
FirewallRule allow udp port 67
FirewallRule allow tcp port 67
}
FirewallRuleSet locked-users {
FirewallRule block to 0.0.0.0/0
}

**Comment by paolo279** [comment] 2016-06-29 14:54
I have the same problem with all ios recent version. I have already tried to add "iptables -t filter -A WiFiDog_br-lan_AuthServers -d xxxx -j DROP "  and with add this to firewall conf setting:
FirewallRule allow tcp to apple.com
 FirewallRule allow tcp to icloud.com

but nothing

no one was able to solve the same problem ??

**Comment by icersg** [comment] 2016-10-21 09:51
@paolo279, have you found a solution? I also have this issue recently. I tried both openwrt 14.07 and 15.05.1 with wifidog 1.2.1 and 1.3.0. It doesn't work most of the iPhones (for example iPhone 6 with iOS 9.3). When an iPhone connects to our wifi, it doesn't popup the login page. However the same wifi works perfectly for iPad, Macbook and Android.

Any suggestions?
