### ISSUE TITLE
The ping thread cannot be executed periodically

### ISSUE THREAD

**Issue by wangyonghe** [wifidog/wifidog-gateway#12] opened 2013-11-01 02:43 UTC
```c
while (1) {
		/* Make sure we check the servers at the very begining */
		debug(LOG_DEBUG, "Running ping()");
		ping();
		
		/* Sleep for config.checkinterval seconds... */
		timeout.tv_sec = time(NULL) + config_get_config()->checkinterval;
		timeout.tv_nsec = 0;

		/* Mutex must be locked for pthread_cond_timedwait... */
		pthread_mutex_lock(&cond_mutex);
		
		/* Thread safe "sleep" */
		pthread_cond_timedwait(&cond, &cond_mutex, &timeout);

		/* No longer needs to be locked */
		pthread_mutex_unlock(&cond_mutex);
	}
```
The ping function executed once.

**Comment by acv** [comment] 2015-03-12 02:56
`pthread_cond_timedwait()` is basically a sleep that is guaranteed thread safe, it will wake up only once the timeout happens or once the mutex is unlocked, since the thread holds the mutex, it will wake up only on time out. `sleep()` is not thread safe.

**Comment by acv** [comment] 2015-03-12 04:19
On Ubuntu, the code as-is pings every CheckInterval seconds. I suggest closing this issue unless the specific run-time environment (Kernel, Libc version, distro) can be specified.

**Comment by mhaas** [comment] 2015-03-12 12:37
Just tested this on OpenWrt Barrier Breaker on ar71xx with CheckInterval set to 1. The server is ping'ed every second.

Please get back to us if you have details on reproducing the issue.

**Closed by mhaas** 2015-03-12 12:37 UTC
